### ISSUE TITLE
Add Hotword Based Wakeup

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_hardware#5]
Now, that prototype is almost ready, next step is to add Hotword based wakeup using "Susi" as hotword

**Comment by mariobehling** [comment]
Please follow up here, what technologies you are using and experimenting with.

**Comment by betterclever** [comment]
**Already tested**
CMU Sphinx (Pocketsphinx) -
Issues - 
1. Slow recognition.
2. Not easy to train via Audio Samples (Like we train Google Assistant: by speaking "Ok Google" 3 times)
3. False positives on slow dictionary.
4. Negative results/ wrong detection on large dictionary.

Currently Testing:
Python Hotword Recogniton (https://github.com/sakethgsharma/HotWordDetection)
Advantages:
1. Training based recognition
2. Fairly correct results if training done right.

Problems being faced:
1. False positive results sometimes.
2. Figuring out a way for continuous detection.
3. Error while detection after training sometimes. (Will update with logs)

**Comment by betterclever** [comment]
Pertaining to problems in Python Hotword Recognition Library, I switched back to Pocketsphinx for hotword. 
After, some adjustments in kws threshold value, the detection is fine now (mostly).
Yet, to eradicate false positive results though.
